### ISSUE TITLE
MAC Fuses on iMX6UL

### ISSUE THREAD

**Issue by StehleJochen** [f-secure-foundry/crucible#5]
Hi,
how could i burn the second MAC addres ? in the yaml file of the imx6ul is only one MAC described?

**Comment by abarisani** [comment]
There is only one fuse for the MAC address. The second one becomes the first one plus 1 but in the end it is up to the driver on how this information is used.

**Comment by StehleJochen** [comment]
Hello,
no that seams not correct. But I found a solution: changed the yaml like this an it worked fine.
  OCOTP_MAC0:
    bank: 4
    word: 2
    fuses:
      MAC1_ADDR:
        offset: 0
        len: 48
      MAC1_ADDR[47:16]:
        offset: 0
        len: 32
  OCOTP_MAC1:
    bank: 4
    word: 3
    fuses:
      MAC1_ADDR[15:0]:
        offset: 0
        len: 16
      MAC2_ADDR:
        offset: 16
        len: 48
      MAC2_ADDR[47:32]:
        offset: 16
        len: 16

  OCOTP_MAC:
    bank: 4
    word: 4
    fuses:
      MAC2_ADDR[31:0]:
        offset: 0
        len: 32


Von: Andrea Barisani <notifications@github.com>
Gesendet: Mittwoch, 22. April 2020 10:49
An: f-secure-foundry/crucible <crucible@noreply.github.com>
Cc: Stehle Jochen stj - Theben AG <jochen.stehle@theben.de>; Author <author@noreply.github.com>
Betreff: Re: [f-secure-foundry/crucible] MAC Fuses on iMX6UL (#5)


There is only one fuse for the MAC address. The second one becomes the first one plus 1 but in the end it is up to the driver on how this information is used.

**Comment by abarisani** [comment]
Ok, then I gathered incorrect information. I will address this in the fusemap.

**Comment by abarisani** [comment]
There is evidence to support this in:

https://github.com/u-boot/u-boot/blob/master/arch/arm/mach-imx/mac.c

As well as:

https://wiki.phytec.com/pages/releaseview.action?pageId=158144808#L844e.A2i.MX6UL/ULLBSPReferenceManual-On-ChipOTPController(OCOTP_CTRL)-eFuses

However official information remains nowhere to be seen in the reference manual.

I am happy to add the second fuse mentioning these references, however it seems to me that the bit order (which you suggest according to the phytec link) is not consistent with our current fusemap.

I changed the order in [this commit](https://github.com/f-secure-foundry/crucible/commit/8c13efb09aa1b3cf299359f9826d36a2a33776ad) following information from IMX6SDLRM.

I guess the interpretation is up to the specific driver, I will investigate and fix accordingly.

**Comment by abarisani** [comment]
We finally tested this (thanks to @andrejro), fixed in https://github.com/f-secure-foundry/crucible/commit/734a68f3c1d50d7f0914f390f52f358d6669c345

```
eth0: link/ether 00:04:9f:05:ba:b0
eth1: link/ether 00:04:9f:05:ba:af

# crucible -m IMX6ULL -r 1 -b 16 read MAC1_ADDR
soc:IMX6ULL ref:1 otp:MAC1_ADDR op:read addr:0x88 off:0 len:48 val:0x00049f05baaf
# crucible -m IMX6ULL -r 1 -b 16 read MAC2_ADDR
soc:IMX6ULL ref:1 otp:MAC2_ADDR op:read addr:0x8c off:16 len:48 val:0x00049f05bab0
```
