### ISSUE TITLE
Missing SJC fuses in i.MX8MM

### ISSUE THREAD

**Issue by kotylamichal** [f-secure-foundry/crucible#6]
Hi, 
Missing in the crucible i.MX8MM fuse map `JTAG_SMODE` and `SJC_DISABLE` are described on the NXP forum:

https://community.nxp.com/t5/i-MX-Processors/DIR-BT-DIS-and-others/m-p/1220615/highlight/true#M168363

**Comment by andrejro** [comment]
Fuses added in https://github.com/f-secure-foundry/crucible/commit/642824867724cfb480ec0acfad350d0a697c5604.
Thanks!
