### ISSUE TITLE
NXP i.MX 8M Plus Quad example

### ISSUE THREAD

**Issue by Oquirella** [f-secure-foundry/crucible#7]
Hi,

Can you provide an example to program the fuses of a  i.MX 8M Plus Quad to a closed configuration?

**Comment by andrejro** [comment]
Hi, we do not provide the support how to configure a specific device. The fusing is an
irreversible operation and can brick the device. It is important that the user has fully understood
the specific p/n reference manual and how to blow specific fuses with crucible.
