### ISSUE TITLE
Incorrect fusemaps for IMX8MP

### ISSUE THREAD

**Issue by Oquirella** [f-secure-foundry/crucible#8]
JTAG_MODE should be JTAG_SMODE

I can't get my hands on "Security Reference Manual for i.MX 8M Plus Applications Processor"
Maybe there are other fuses that need to be added/corrected.

**Comment by andrejro** [comment]
Fixed in https://github.com/f-secure-foundry/crucible/commit/2d3048bd8df38bb98da29ac323062ff590b524b0.
Thanks
